/*///////////////////////////////// ABOUT \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*\

  Main Entry Point for WebPlay Browser Client
  see @webplay-server.mts for build and serve code

  QUICK START:
  Put your files into the scripts directory and import them to test in
  the browser. Changes to source files will trigger a rebuild and reload.

\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ * /////////////////////////////////////*/

import { ConsoleStyler } from 'ursys';
import * as SERVICE from './webplay-svc-client.ts';
import './webplay-client-imports'; // autogenerated by @webplay-server.mts

/// CONSTANTS /////////////////////////////////////////////////////////////////
/// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
const PR = ConsoleStyler('WEBPLAY', 'TagCyan');
const LOG = console.log.bind(console);

/// RUNTIME ///////////////////////////////////////////////////////////////////
/// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(async () => {
  SERVICE.UR_StartLifecycle(); // force load of module
  LOG(...PR('WEBPLAY READY'));
})();
