/*///////////////////////////////// ABOUT \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\*\

  Main Entry Point for WebPlay Browser Client
  see @webplay-server.mts for build and serve code

  QUICK START:
  Put your files into the scripts directory and import them to test in
  the browser. Changes to source files will trigger a rebuild and reload.

\*\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\ * /////////////////////////////////////*/

import { ConsoleStyler } from '@ursys/core';
import * as SERVICE from './webplay-client-services.ts';
import './webplay-client-imports.ts'; // autogenerated by @webplay-server.mts

/// CONSTANTS /////////////////////////////////////////////////////////////////
/// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
const PR = ConsoleStyler('WebPlay', 'TagPurple');
const LOG = console.log.bind(console);

/// RUNTIME ///////////////////////////////////////////////////////////////////
/// - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
(async () => {
  LOG(...PR('WebPlay Client Loaded'));
})();
