#!/bin/sh
# URTEST is a CLI development task runner that invokes the URSYS CLI build library
# it lives inside of the _ur directory

# Portable Echo
prln() {
  printf "%s\n" "$*"
}

# PATH SETTINGS
SCRIPT_DIR=$(dirname "$(realpath "$0")")
UR_BUILD="$SCRIPT_DIR/"
CLI_BUILD="$SCRIPT_DIR/npm-scripts"
ADDONS_LIB="$SCRIPT_DIR/../_ur_addons"
TEST_BUILD="$SCRIPT_DIR/../_ur_addons/loki"

# TERMINAL COLORS
DIM=$(tput dim)
YELLOW=$(tput setaf 3)
RESET=$(tput sgr0)
BGBLUE=$(tput setab 4)$(tput setaf 7)
BRITE=$(tput bold)


usage() {
    COMMANDS="build test"
    ADDONS=""
    a_dirs=$(find "$ADDONS_LIB" -mindepth 1 -maxdepth 1 -type d -name "[!_]*" -exec basename {} \;)
    a_dirs=$(prln "$a_dirs" | tr '\n' ' ')
    for dir in $a_dirs; do
      if [ "$dir" != "node_modules" ]; then
        ADDONS="$ADDONS $dir"
      fi
    done
    ADDONS=$(prln $ADDONS)
    prln "usage:     ${yellow}ur [command | addon]${RESET}${DIM}"
    prln "commands   $COMMANDS"
    prln "addons     $ADDONS"
    prln "${RESET}"
    exit 1
}

# Make sure NodeJS is installed
if ! command -v node > /dev/null 2>&1; then
    prln "Node.js not found. Please ensure it's installed."
    exit 1
fi

#
# If no arguments provided or unknown option, display usage
#
if [ $# -eq 0 ]; then
  usage
fi

#
# handle built-in commands
# note: Use --max-old-space-size to limit memory (values are in MB, so 128 is 128MB)
#
DEBUG="--inspect-brk" # use --inspect-brk to break on first line
TSOPTS="--transpile-only" # use --no-cache to force a full rebuild tsnode (disables typecheck)
case "$1" in
    build)
        # (1) always build library first
        npx ts-node-esm $TSOPTS $CLI_BUILD/@build-core.mts 2>&1 | cat
        # (2) add additional tasks here (eventually can be command args)
        npx ts-node-esm $TSOPTS $CLI_BUILD/@build-addons.mts 2>&1 | cat
        # (3) build the type exports with rollup (not working due to type conflicts)
        # npx tsc --project ../.types.node.tsconfig.json 
        # npx tsc --project ../.types.web.tsconfig.json 
        # npx rollup -c ../.types.config.js
        exit 0;
        ;;

    test)
        # get additional argument after 'test' into $option
        npx ts-node-esm $TSOPTS  $CLI_BUILD/@build-core.mts 2>&1 | cat
        PROMPT="${BGBLUE} UR TEST ${RESET}"
        if [ "$2" = "core" ]; then
            prln "${PROMPT} running ${BRITE}ursys core tests${RESET}"
            npx vitest --config ./tests/vitest.core.config.mts
        elif [ "$2" = "addons" ]; then
            prln "${PROMPT} running ${BRITE}ursys addons tests${RESET}"
            npx vitest --config ./tests/vitest.addons.config.mts
        elif [ "$2" = "webplay" ]; then
            prln "${PROMPT} running ${BRITE}ursys webplay tests${RESET}"
            npx vitest --config ./tests/vitest.webplay.config.mts
        elif [ -z "$2" ]; then
            prln "${PROMPT} running ${BRITE}ursys core and addon tests${RESET}"
            npx vitest --config ./tests/vitest.all.config.mts
        else
            prln "${YELLOW}unknown test option: '$2'${RESET}"
            exit 1;
        fi
        exit 0;
        ;;
esac

#
# if we got this far, then none of the built-in commands above were run, so 
# load the designated addon directory in $1 and pass the remaining arguments
# to our loader scripts
# build the core first, then load the addon
npx ts-node-esm $TSOPTS $CLI_BUILD/@build-core.mts 2>&1 | cat
npx ts-node-esm $TSOPTS $ADDONS_LIB/@load-addon.mts "$@"
# to debug the addon loader, remove the TSOPTS (--transpile-only)
